/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.ZodObject
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * Use parameters to search for Zod objects. Without any parameters, return all Zod objects.
   * 
   * Expected answers:
   *   code 200 : Seq[ZodObject] (search results matching criteria)
   *   code 400 :  (bad input parameter)
   * 
   * @param searchString pass an optional search string for looking up zod objects
   * @param skip number of records to skip for pagination
   * @param limit maximum number of records to return
   */
  def searchZodObjects(searchString: Option[String] = None, skip: Option[Int] = None, limit: Option[Int] = None): ApiRequest[Seq[ZodObject]] =
    ApiRequest[Seq[ZodObject]](ApiMethods.GET, "https://virtserver.swaggerhub.com/pgleghorn/test/1.0.0", "/zod", "application/json")
      .withQueryParam("searchString", searchString)
      .withQueryParam("skip", skip)
      .withQueryParam("limit", limit)
      .withSuccessResponse[Seq[ZodObject]](200)
      .withErrorResponse[Unit](400)
      

}

