---
swagger: "2.0"
info:
  description: "Simple API for retrieving Zod objects"
  version: "1.0.0"
  title: "Zod API"
  contact:
    email: "pgleghorn@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/pgleghorn/test/1.0.0"
schemes:
- "https"
- "http"
paths:
  /zod:
    get:
      summary: "search Zod objects"
      description: "Use parameters to search for Zod objects. Without any parameters,\
        \ return all Zod objects."
      operationId: "searchZodObjects"
      produces:
      - "application/json"
      parameters:
      - name: "searchString"
        in: "query"
        description: "pass an optional search string for looking up zod objects"
        required: false
        type: "string"
      - name: "skip"
        in: "query"
        description: "number of records to skip for pagination"
        required: false
        type: "integer"
        minimum: 0
        format: "int32"
      - name: "limit"
        in: "query"
        description: "maximum number of records to return"
        required: false
        type: "integer"
        maximum: 500
        minimum: 0
        format: "int32"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ZodObject"
        400:
          description: "bad input parameter"
definitions:
  ZodObject:
    type: "object"
    required:
    - "id"
    - "lastUpdatedDate"
    - "name"
    - "type"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      type:
        type: "string"
        example: "km"
      name:
        type: "string"
        example: "test km object"
      lastUpdatedDate:
        type: "string"
        example: "2016-08-29T09:12:33.001Z"
